using System;
using pruebaPelicula.Shared.Entity;
using System.Collections.Generic;

namespace pruebaPelicula.Client.Services
{
    public class ServiceMovie : IServiceMovie
    {
        public List<Movie> GetMovies()
        {
            return new List<Movie>
            {
                new Movie( 1, "Shang-Chi y la leyenda de los diez anillos", 1, 30, false, "Images/Movies/Shang-Chi y la leyenda de los diez anillos.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 10 ) { Premier = new DateTime(2021,01,05) },
                new Movie( 2, "Spider-Man: Un nuevo universo", 1, 30, true, "Images/Movies/SpiderMan - Un nuevo universo.png",  "https://www.youtube.com/watch?v=-RSseKOWpEQ", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 10 ) { Premier = new DateTime(2021,02,06) },
                new Movie( 3, "Free Guy", 1, 30, false, "Images/Movies/Free Guy.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 10 ) { Premier = new DateTime(2021,03,07) },
                new Movie( 4, "Interstellar", 1, 30, true, "Images/Movies/Interstellar.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 9 ) { Premier = new DateTime(2021,04,08) },
                new Movie( 5, "Jungle Cruise", 1, 30, false, "Images/Movies/Jungle Cruise.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 8 ) { Premier = new DateTime(2021,05,09) },
                new Movie( 6, "Fast & Furious 9", 1, 30, true, "Images/Movies/Fast & Furious 9.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 7 ) { Premier = new DateTime(2021,06,10) },
                new Movie( 7, "Origen", 1, 30, false, "Images/Movies/Origen.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 8 ) { Premier = new DateTime(2021,07,11) },
                new Movie( 8, "Forrest Gump", 1, 30, true, "Images/Movies/Forrest Gump.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 9 ) { Premier = new DateTime(2021,08,12) },
                new Movie( 9, "Your Name.", 1, 30, false, "Images/Movies/Your Name.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 10 ) { Premier = new DateTime(2021,09,13) },
                new Movie( 10, "El padrino", 1, 30, true, "Images/Movies/El padrino.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 7 ) { Premier = new DateTime(2021,10,14) },
                new Movie( 11, "Joker", 1, 30, false, "Images/Movies/Joker.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 9 ) { Premier = new DateTime(2021,11,15) },
                new Movie( 12, "Malditos bastardos", 1, 30, true, "Images/Movies/Malditos bastardos.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 7 ) { Premier = new DateTime(2021,12,16) },
                new Movie( 13, "Vengadores: Endgame", 1, 30, false, "Images/Movies/Vengadores - Endgame.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 10 ) { Premier = new DateTime(2021,01,17) },
                new Movie( 14, "La familia Bigfoot", 1, 30, true, "Images/Movies/La familia Bigfoot.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 6 ) { Premier = new DateTime(2021,02,18) },
                new Movie( 15, "El hombre elefante", 1, 30, false, "Images/Movies/El hombre elefante.jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 8 ) { Premier = new DateTime(2021,03,19) },
                new Movie( 16, "Jurassic Park (Parque Jurásico)", 1, 30, true, "Images/Movies/Jurassic Park (Parque Jurásico).jpg",  "https://www.youtube.com/watch?v=BD77EOU8N3o", "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe illo earum voluptatum temporibus doloremque quidem explicabo deserunt, quos, laboriosam culpa veniam aut ipsam eveniet! Quia quo similique dolorem adipisci expedita.", 10 ) { Premier = new DateTime(2021,04,20) }
            };
        }
    }
}